options:
  formatter: stylish
  merge-default-rules: false
rules:
  attribute-quotes:
    - 2
    - include: true
  bem-depth:
    - 2
    - max-depth: 4
  border-zero:
    - 2
    - convention: '0'
  brace-style:
    - 2
    - stroustrup
  no-misspelled-properties:
    - 1
    - true
  one-declaration-per-line:
    - 2
    - true
  single-line-per-selector:
    - 2
    - true
  trailing-semicolon:
    - 2
    - include: true
  url-quotes:
    - 2
    - true
  variable-name-format:
    - 2
    - allow-leading-underscore: true
    - convention: hyphenatedlowercase
  zero-unit:
    - 2
    - include: false
